name: loyola
description: A Loyola Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.2
  shared_preferences: ^2.0.17
  flutter_otp_text_field: ^1.1.1
  permission_handler: ^10.2.0
  otp_text_field: ^1.1.3
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.2
  get: ^4.6.5
  dropdown_button2: ^1.9.3
  share_plus: ^6.3.1
  modal_bottom_sheet: ^2.1.2
  image_picker: ^0.8.6+3
  flutter_html: ^3.0.0-alpha.6
  file_picker: ^5.2.6
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  toggle_switch: ^2.0.1
  some_calendar: ^1.3.0
  floating_bottom_navigation_bar: ^1.5.2
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  flutter_local_notifications: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf